<?php


function travel_proximity_form_alter(&$form, &$form_state, $form_id){


  if($form_id === "views_exposed_form" && isset($form['#info']['filter-field_geofield_distance'])){
    global $user;

    $user_data = user_load($user->uid);
    $travel_distance = field_get_items('user', $user_data, 'field_travel_distance');
    $user_geofield = field_get_items('user', $user_data, 'field_geofield');

    $form['field_geofield_distance']['#default_value']['distance'] = $travel_distance[0]['value'];
    $form['field_geofield_distance']['#default_value']['origin'] = $user_geofield[0]['geom'];
  }
}
