<?php
function notify_friends_request_form_alter(&$form, &$form_state, $form_id){
  //hide default widget. there is a widget alter hook as well, perhaps this could work better?

  //replaces on + shift request form the list of people to only those current user is friends with
  if(isset($form['type'])){
    if($form['type']['#value'] === 'shift_request'){
      global $user;

      module_load_include('module', 'user_relationships', 'user_relationships');
      module_load_include('pages.inc', 'user', 'user');

      $user_friends = user_relationships_load(array("user" => $user->uid));

      $user_friend_id_output = [];
      $user_friend_associative_id_name = [];

      foreach ($user_friends as $key => $user_friend) {
        if($user_friend->requester_id === $user->uid){
          $user_friend_id_output[] = $user_friend->requestee_id;
        }
        if($user_friend->requestee_id === $user->uid){
          $user_friend_id_output[] = $user_friend->requester_id;
        }
      }

      foreach ($user_friend_id_output as $key => $user_id) {
        $friend_data = user_load($user_id);
        $friend_name = $friend_data->name;
        $user_friend_associative_id_name[$user_id] = $friend_name;
      }

        $form['field_friends_of_poster1']['und']['#options'] = $user_friend_associative_id_name;
        $form['field_friends_of_poster1']['#attributes']['checked'] = 'checked';
    }
  }
}
